service:
  name: roles-auths-soap-service
spring:
  application.name: roles-auths-soap-service
wsdl_filter_request_path: /rova/wsdl
wsdl_filter_resource_path: wsdl
wsdl_filter_request_files: authorization.wsdl,authorizationList.wsdl,delegate.wsdl,orgroles.wsdl,xroad6identifiers.xsd,xroad6.xsd
hpa_client_enabled: true
ypa_client_enabled: true

eureka:
  client:
    register-with-eureka: false

roles-auths-engine-hpa:
  ribbon:
    ServerListRefreshInterval: 60000
    DeploymentContextBasedVipAddresses: roles-auths-engine
    non-secure-port: 0
    eureka:
      enabled: false
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    NFLoadBalancerRuleClassName: fi.vm.kapa.rova.engine.EngineLoadbalancerRule
roles-auths-engine-ypa:
  ribbon:
    ServerListRefreshInterval: 60000
    DeploymentContextBasedVipAddresses: roles-auths-engine
    non-secure-port: 0
    eureka:
      enabled: false
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    NFLoadBalancerRuleClassName: fi.vm.kapa.rova.engine.EngineLoadbalancerRule

hystrix:
  command:
    default:
      circuitBreaker:
        enabled: false
        errorThresholdPercentage: 80
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 90000
          semaphore:
            maxConcurrentRequests: 100
      fallback:
        enabled: false

